[package]
name = "recon"
version = "0.4.1-alpha.1"
description = "Recon - Competitive Stretched Resolution & Utility"
authors = ["Youssef Adel <contact@recon.qd.je>"]
license = "Proprietary"
repository = "https://github.com/youssefvdel/Recon"
homepage = "https://recon.qd.je"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
winreg = "0.52"
tauri = { version = "2.11.3", features = ["tray-icon"] }
tauri-plugin-log = "2"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Devices_Display",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Properties",
    "Win32_UI_Shell",
    "Win32_Security_Cryptography",
] }
tauri-plugin-mcp-bridge = "0.13.0"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
ini-preserve = "0.1.3"

